### ISSUE TITLE
How to get watertight meshes

### ISSUE THREAD

**Issue by MayuOshima** [otaheri/GRAB#6]
Hello, first, thanks for your great work!

It seems that the meshes I get from your method are not watertight.
I just do [os_mesh = o_mesh + s_mesh] and then save os_mesh as a .obj file. o_mesh is from line 95 in example/visualize_grab.py and s_mesh is from line 98 in example/visualize_grab.py.

So is there any watertight version? Or could you please show me how to get watertight .obj files?

Thank you :)

**Comment by otaheri** [comment]
Hi @MayuOshima,

We released all the object meshes as water-tight ones,  so the problem is not from the objects. The problem is most probably coming from the body mesh as in the eye areas there are two holes. The quickest solution would be to save the body mesh, make it watertight using blender or MeshLab, and then merge it with the object.

I hope this helps, good luck :)

**Comment by MayuOshima** [comment]
OK. 
Thanks for your reply!
I will have a try!
