### ISSUE TITLE
Outliers in the table pose

### ISSUE THREAD

**Issue by jaraujo98** [otaheri/GRAB#7]
Hello! Thanks for the great dataset!

I've noticed that some sequences have outliers in the table position. The rendered videos confirm their presence (see, for example, "grab\s7\pyramidsmall_pass_1", shortly after the person grabs the object). To get the full list of sequences with outliers you can use the following snippet. I get 242 sequences when it finishes.

```
tol = 1e-3
for file in glob.glob(PATH_TO_GRAB + r"\*\*.npz"):
    data = parse_npz(file)
    parms = data.table.params
    if np.max(np.linalg.norm(np.diff(parms.global_orient,axis=0),axis=1)) > tol: print(file)
```

Are there any plans to clean these sequences, or a recommended way to clean the data?

Thanks!

**Comment by otaheri** [comment]
Hi @jaraujo98,
Thanks for reporting this issue, we are already aware of this problem, but as we thought this is not the focus of the project we didn't resolve it so far. The quickest solution would be: If you know which frames have wrong table parameters, just replace the parameters with one of the correct frames. This solution works because the table is always fixed (except for doorknob sequences :D) and is not supposed to move, so you will get an accurate table. The other solution would be to use the raw mocap data that we provided and just use the markers on the table to get correct table poses. 

I hope these solutions help,
Best,
Omid
